# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 10:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='master_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cltv', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('engagement', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.CharField(blank=True, max_length=100, null=True)),
                ('high_converter', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('churn', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('cu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='master_table',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Personal'),
        ),
    ]
