# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_message', models.CharField(max_length=999)),
                ('chat_time', models.CharField(max_length=999)),
                ('chat_sendby', models.CharField(max_length=100)),
            ],
        ),
    ]
