# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDbModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(blank=True, max_length=50, null=True)),
                ('database_type', models.CharField(blank=True, max_length=200, null=True)),
                ('host', models.CharField(blank=True, max_length=200, null=True)),
                ('usern', models.CharField(blank=True, max_length=16, null=True)),
                ('passw', models.CharField(blank=True, max_length=50, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
