# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContactMappingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_table_name', models.CharField(max_length=200)),
                ('cust_id', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('facebook_id', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMasterMappingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_table_name', models.CharField(max_length=200)),
                ('customer_id', models.CharField(max_length=200)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventLogMappingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_table_name', models.CharField(max_length=200)),
                ('cust_id', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('action_type', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=200)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventMasterMappingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_table_name', models.CharField(max_length=200)),
                ('action_type', models.CharField(max_length=200)),
                ('action_name', models.CharField(max_length=200)),
                ('action_category_id', models.CharField(max_length=200)),
                ('action_category_name', models.CharField(max_length=200)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMasterMappingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_table_name', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('subcategory_id', models.CharField(max_length=200)),
                ('subcategory_name', models.CharField(max_length=200)),
                ('category_id', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=200)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMasterMappingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_table_name', models.CharField(max_length=200)),
                ('cust_id', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=200)),
                ('revenue', models.CharField(max_length=200)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
