# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20161216_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermastermappingmodel',
            name='birthday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermastermappingmodel',
            name='create_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionmastermappingmodel',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionmastermappingmodel',
            name='renewal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
