# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_auto_20161227_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontactmappingmodel',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customercontactmappingmodel',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
